/* The following code was generated by JFlex 1.4.3 on 08.09.13 01:11 */

/*
 * AssemblerTxTokenMaker.java - An object that can take a chunk of text and
 * return a linked list of tokens representing Toshiba Tx assembler.
 * Based on AssemblerX86TokenMaker.java by Robert Futrell
 */
package com.nikonhacker.gui.component.sourceCode.syntaxHighlighter;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexTokenMaker;
import org.fife.ui.rsyntaxtextarea.DefaultToken;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMaker;

import javax.swing.text.Segment;
import java.io.IOException;


/**
 * This class takes plain text and returns tokens representing Tx
 * assembler.<p>
 *
 * This implementation was created using
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1; however, the generated file
 * was modified for performance.  Memory allocation needs to be almost
 * completely removed to be competitive with the handwritten lexers (subclasses
 * of <code>AbstractTokenMaker</code>, so this class has been modified so that
 * Strings are never allocated (via yytext()), and the scanner never has to
 * worry about refilling its buffer (needlessly copying chars around).
 * We can achieve this because RText always scans exactly 1 line of tokens at a
 * time, and hands the scanner this line as an array of characters (a Segment
 * really).  Since tokens contain pointers to char arrays instead of Strings
 * holding their contents, there is no need for allocating new memory for
 * Strings.<p>
 *
 * The actual algorithm generated for scanning has, of course, not been
 * modified.<p>
 *
 * If you wish to regenerate this file yourself, keep in mind the following:
 * <ul>
 *   <li>The generated AssemblerTxTokenMaker.java</code> file will contain two
 *       definitions of both <code>zzRefill</code> and <code>yyreset</code>.
 *       You should hand-delete the second of each definition (the ones
 *       generated by the lexer), as these generated methods modify the input
 *       buffer, which we'll never have to do.</li>
 *   <li>You should also change the declaration/definition of zzBuffer to NOT
 *       be initialized.  This is a needless memory allocation for us since we
 *       will be pointing the array somewhere else anyway.</li>
 *   <li>You should NOT call <code>yylex()</code> on the generated scanner
 *       directly; rather, you should use <code>getTokenList</code> as you would
 *       with any other <code>TokenMaker</code> instance.</li>
 * </ul>
 *
 * @author Robert Futrell
 * @version 0.2
 *
 */

public class AssemblerTxTokenMaker extends AbstractJFlexTokenMaker implements TokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\7\1\0\1\10\23\0\1\10\1\12\1\4\1\0"+
    "\1\47\1\12\1\12\1\5\2\0\1\12\1\12\1\0\1\12\1\0"+
    "\1\12\1\15\1\32\1\50\1\51\1\46\1\2\1\2\1\2\1\46"+
    "\1\2\1\11\1\6\1\12\1\12\1\12\2\0\1\13\1\22\1\14"+
    "\1\20\1\25\1\3\1\42\1\40\1\16\1\45\1\31\1\23\1\35"+
    "\1\21\1\33\1\36\1\44\1\24\1\30\1\27\1\17\1\37\1\41"+
    "\1\26\1\43\1\34\3\0\1\12\1\1\1\0\1\13\1\22\1\14"+
    "\1\20\1\25\1\3\1\42\1\40\1\16\1\45\1\31\1\23\1\35"+
    "\1\21\1\33\1\36\1\44\1\24\1\30\1\27\1\17\1\37\1\41"+
    "\1\26\1\43\1\34\1\0\1\12\1\0\1\12\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\4\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\5\1\1\10\14\1\1\10\1\1\1\11\2\0\1\1"+
    "\1\12\1\1\1\13\1\14\11\1\1\15\1\16\1\1"+
    "\2\15\16\1\1\16\1\1\2\16\1\1\2\12\11\1"+
    "\1\16\5\1\1\16\1\1\1\16\11\1\1\10\2\0"+
    "\2\1\1\16\3\1\1\16\1\10\2\1\1\10\13\1"+
    "\2\10\3\1\2\16\7\1\1\16\2\1\1\10\3\12"+
    "\2\17\1\1\1\16\1\1\2\10\2\1\1\20\2\1"+
    "\1\10\3\1\1\0\6\1\1\0\2\1\1\0\1\1"+
    "\2\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\52\0\u0150\0\52\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\52"+
    "\0\u04c2\0\u04ec\0\u0516\0\124\0\u0540\0\52\0\52\0\u056a"+
    "\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba"+
    "\0\u0516\0\u06e4\0\u070e\0\124\0\u0540\0\u0738\0\u0762\0\u078c"+
    "\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc"+
    "\0\u0906\0\u0930\0\u095a\0\124\0\u0984\0\u09ae\0\u09d8\0\u0a02"+
    "\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0ad4\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0984\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e"+
    "\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee"+
    "\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\124"+
    "\0\u103e\0\u1068\0\u1092\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164"+
    "\0\u118e\0\u11b8\0\u11e2\0\u120c\0\u1236\0\u1260\0\u128a\0\u12b4"+
    "\0\u12de\0\u1308\0\u1332\0\u135c\0\u1386\0\u13b0\0\u13da\0\u1404"+
    "\0\u142e\0\u1458\0\u1482\0\u14ac\0\u14d6\0\u1500\0\u152a\0\u1554"+
    "\0\52\0\u157e\0\u15a8\0\u15d2\0\u15fc\0\u09ae\0\u15fc\0\u1626"+
    "\0\u1650\0\u167a\0\u16a4\0\u16ce\0\124\0\u16f8\0\u1722\0\u174c"+
    "\0\u1776\0\u17a0\0\u17ca\0\u17f4\0\u181e\0\u1848\0\u1872\0\u189c"+
    "\0\u18c6\0\u18f0\0\u191a\0\u1944\0\u196e\0\u1998\0\u19c2\0\u04c2"+
    "\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\2\1\13\1\14\1\15\1\4\1\16\1\3"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\3\1\4\1\30\1\31\1\32\1\33\2\3"+
    "\1\34\2\3\1\35\1\36\1\4\1\37\2\4\53\0"+
    "\3\3\5\0\1\40\1\0\34\3\1\0\2\3\1\0"+
    "\1\41\2\42\5\0\1\40\1\0\3\42\2\41\1\42"+
    "\1\41\1\42\2\41\1\42\4\41\1\42\13\41\1\42"+
    "\1\0\2\42\1\0\1\3\2\43\5\0\1\40\1\0"+
    "\3\43\2\3\1\43\1\3\1\43\2\3\1\43\4\3"+
    "\1\43\3\3\1\44\2\3\1\45\4\3\1\43\1\0"+
    "\2\43\4\6\1\46\45\6\5\7\1\47\44\7\7\10"+
    "\1\0\42\10\10\0\1\12\42\0\1\3\2\43\5\0"+
    "\1\40\1\0\1\43\1\50\1\43\2\3\1\51\1\52"+
    "\1\43\2\3\1\43\4\3\1\43\13\3\1\43\1\0"+
    "\2\43\1\0\1\3\1\43\1\53\5\0\1\40\1\0"+
    "\1\54\2\43\2\3\1\43\1\3\1\43\1\55\1\3"+
    "\1\43\1\3\1\56\2\3\1\43\2\3\1\57\10\3"+
    "\1\43\1\0\2\43\1\0\3\3\5\0\1\40\1\0"+
    "\12\3\1\60\21\3\1\0\2\3\1\0\1\3\1\43"+
    "\1\61\5\0\1\40\1\0\3\43\1\62\1\3\1\61"+
    "\1\3\1\61\2\3\1\63\1\3\1\64\2\3\1\43"+
    "\6\3\1\65\2\3\1\64\1\3\1\43\1\0\2\43"+
    "\1\0\3\3\5\0\1\40\1\0\12\3\1\66\5\3"+
    "\1\67\13\3\1\0\2\3\1\0\1\3\1\43\1\70"+
    "\5\0\1\40\1\0\1\71\1\72\1\43\1\73\1\3"+
    "\1\43\1\74\1\43\1\75\1\76\1\77\1\3\1\100"+
    "\1\101\1\3\1\43\7\3\1\102\1\103\2\3\1\43"+
    "\1\0\2\43\1\0\3\3\5\0\1\40\1\0\3\3"+
    "\1\104\1\105\2\3\1\106\15\3\1\106\1\107\5\3"+
    "\1\0\2\3\1\0\1\3\1\44\1\3\5\0\1\40"+
    "\1\0\1\44\1\3\1\44\7\3\1\110\4\3\1\111"+
    "\13\3\1\44\1\0\1\111\1\112\1\0\1\3\2\43"+
    "\5\0\1\40\1\0\3\43\1\104\1\3\1\43\1\3"+
    "\1\43\1\3\1\113\1\43\4\3\1\43\3\3\1\33"+
    "\7\3\1\43\1\0\2\43\1\0\3\3\5\0\1\40"+
    "\1\0\20\3\1\30\13\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\6\3\1\114\1\115\1\116\1\3"+
    "\1\117\13\3\1\45\1\120\4\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\121\3\3\1\122\1\123"+
    "\1\3\1\124\1\125\1\126\1\127\1\3\1\130\1\131"+
    "\5\3\1\44\1\3\1\104\1\132\1\3\1\133\3\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\11\3"+
    "\1\134\22\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\12\3\1\127\21\3\1\0\2\3\1\0\2\3"+
    "\1\135\5\0\1\40\1\0\1\136\2\3\1\137\1\140"+
    "\7\3\1\135\1\141\2\3\1\142\13\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\1\3\1\44\32\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\1\143"+
    "\17\3\1\144\13\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\26\3\1\45\5\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\145\10\3\1\146\22\3"+
    "\1\0\2\3\3\0\1\147\47\0\3\41\5\0\1\40"+
    "\1\0\34\41\1\0\2\41\1\0\1\41\2\150\5\0"+
    "\1\40\1\0\3\150\2\41\1\150\1\41\1\150\2\41"+
    "\1\150\4\41\1\150\13\41\1\150\1\0\2\150\1\0"+
    "\1\3\2\151\5\0\1\40\1\0\3\151\2\3\1\151"+
    "\1\3\1\151\2\3\1\151\4\3\1\151\13\3\1\151"+
    "\1\0\2\151\1\0\3\3\5\0\1\40\1\0\20\3"+
    "\1\144\13\3\1\0\2\3\1\0\1\3\2\151\5\0"+
    "\1\40\1\0\2\151\1\152\2\3\1\151\1\3\1\151"+
    "\2\3\1\151\4\3\1\151\13\3\1\151\1\0\2\151"+
    "\1\0\1\3\2\151\5\0\1\40\1\0\3\151\2\3"+
    "\1\153\1\3\1\151\2\3\1\151\4\3\1\151\13\3"+
    "\1\151\1\0\2\151\1\0\3\3\5\0\1\40\1\0"+
    "\5\3\1\134\26\3\1\0\2\3\1\0\1\3\2\151"+
    "\5\0\1\40\1\0\1\151\1\154\1\151\2\3\1\151"+
    "\1\3\1\151\2\3\1\151\4\3\1\151\13\3\1\151"+
    "\1\0\2\151\1\0\1\3\2\151\5\0\1\40\1\0"+
    "\3\151\1\3\1\155\1\151\1\3\1\151\2\3\1\151"+
    "\4\3\1\151\13\3\1\151\1\0\2\151\1\0\3\3"+
    "\5\0\1\40\1\0\20\3\2\104\12\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\1\3\1\156\32\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\23\3"+
    "\1\134\10\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\11\3\1\44\22\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\24\3\1\157\7\3\1\0\2\3"+
    "\1\0\1\3\2\151\5\0\1\40\1\0\3\151\2\3"+
    "\1\151\1\3\1\151\1\3\1\113\1\151\4\3\1\151"+
    "\13\3\1\151\1\0\2\151\1\0\3\3\5\0\1\40"+
    "\1\0\27\3\1\104\4\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\11\3\1\104\2\3\1\104\6\3"+
    "\1\104\10\3\1\0\2\3\1\0\1\3\2\151\5\0"+
    "\1\40\1\0\3\151\1\73\1\3\1\151\1\3\1\151"+
    "\2\3\1\151\4\3\1\151\13\3\1\151\1\0\2\151"+
    "\1\0\1\3\2\151\5\0\1\40\1\0\3\151\2\3"+
    "\1\151\1\3\1\151\1\160\1\3\1\151\4\3\1\151"+
    "\13\3\1\151\1\0\2\151\1\0\1\3\2\151\5\0"+
    "\1\40\1\0\3\151\2\3\1\151\1\3\1\151\1\161"+
    "\1\3\1\151\4\3\1\151\13\3\1\151\1\0\2\151"+
    "\1\0\3\3\5\0\1\40\1\0\6\3\1\162\25\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\12\3"+
    "\1\163\21\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\12\3\1\164\1\3\1\165\17\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\12\3\1\166\21\3"+
    "\1\0\2\3\1\0\1\3\2\151\5\0\1\40\1\0"+
    "\3\151\2\3\1\151\1\3\1\151\2\3\1\151\1\167"+
    "\3\3\1\151\11\3\1\163\1\3\1\151\1\0\2\151"+
    "\1\0\3\3\5\0\1\40\1\0\6\3\1\170\3\3"+
    "\1\171\2\3\1\167\16\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\12\3\1\167\4\3\1\172\14\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\12\3"+
    "\1\165\1\3\1\164\17\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\14\3\1\173\17\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\3\3\1\104\30\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\4\3"+
    "\1\104\27\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\1\3\1\156\6\3\2\104\22\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\1\174\13\3\1\160"+
    "\1\175\16\3\1\0\2\3\1\0\1\3\1\44\1\3"+
    "\5\0\1\40\1\0\2\3\1\44\14\3\1\44\13\3"+
    "\1\44\1\0\2\44\1\0\3\3\5\0\1\40\1\0"+
    "\2\3\1\44\14\3\1\44\14\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\12\3\1\176\21\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\12\3\1\177"+
    "\21\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\30\3\1\103\3\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\14\3\1\200\17\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\31\3\1\177\2\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\12\3\1\200"+
    "\21\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\5\3\1\201\16\3\1\202\7\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\7\3\1\106\24\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\7\3\1\203"+
    "\16\3\1\45\5\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\10\3\1\204\3\3\1\205\17\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\1\204\7\3"+
    "\1\204\23\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\7\3\1\104\15\3\1\104\6\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\1\206\33\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\1\3\1\60"+
    "\2\3\1\207\27\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\1\3\1\156\6\3\2\104\6\3\1\144"+
    "\13\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\6\3\1\210\6\3\1\211\16\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\3\1\212\6\3\1\213"+
    "\14\3\1\105\6\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\5\3\1\214\5\3\1\104\20\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\6\3\1\104"+
    "\25\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\10\3\1\215\23\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\4\3\1\122\27\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\24\3\1\216\7\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\3\3\1\167"+
    "\30\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\11\3\1\217\22\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\10\3\1\220\23\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\3\1\160\32\3\1\0"+
    "\2\3\2\0\1\221\12\0\1\221\14\0\1\222\13\0"+
    "\1\221\1\0\1\222\1\223\1\0\1\41\2\224\5\0"+
    "\1\40\1\0\3\224\2\41\1\224\1\41\1\224\2\41"+
    "\1\224\4\41\1\224\13\41\1\224\1\0\2\224\1\0"+
    "\1\3\2\225\5\0\1\40\1\0\3\225\2\3\1\225"+
    "\1\3\1\225\2\3\1\225\4\3\1\225\13\3\1\225"+
    "\1\0\2\225\1\0\1\3\2\225\5\0\1\40\1\0"+
    "\3\225\1\226\1\3\1\225\1\3\1\225\2\3\1\225"+
    "\4\3\1\225\13\3\1\225\1\0\2\225\1\0\1\3"+
    "\2\225\5\0\1\40\1\0\3\225\1\106\1\104\1\225"+
    "\1\3\1\225\2\3\1\225\4\3\1\225\13\3\1\225"+
    "\1\0\2\225\1\0\1\3\2\225\5\0\1\40\1\0"+
    "\3\225\2\3\1\225\1\3\1\225\2\3\1\225\4\3"+
    "\1\227\13\3\1\225\1\0\2\225\1\0\3\3\5\0"+
    "\1\40\1\0\15\3\1\230\16\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\17\3\1\104\14\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\4\3\1\104"+
    "\5\3\1\106\21\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\11\3\1\104\22\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\15\3\1\104\16\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\10\3\1\160"+
    "\10\3\1\231\12\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\21\3\1\231\12\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\21\3\1\232\12\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\1\233\33\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\14\3"+
    "\1\104\17\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\12\3\1\234\21\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\31\3\1\234\2\3\1\0\2\3"+
    "\1\0\2\3\1\104\5\0\1\40\1\0\34\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\12\3\1\235"+
    "\21\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\10\3\1\236\23\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\14\3\1\237\17\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\14\3\1\160\17\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\3\3\1\160"+
    "\30\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\3\3\1\240\1\160\27\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\5\3\1\104\26\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\12\3\1\104\21\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\7\3"+
    "\1\241\24\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\24\3\1\104\7\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\3\3\1\106\1\104\27\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\14\3\1\242"+
    "\17\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\7\3\1\104\24\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\1\3\1\104\32\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\3\1\243\32\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\2\3\1\104"+
    "\31\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\20\3\1\104\13\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\5\3\1\106\26\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\14\3\1\106\17\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\6\3\1\104"+
    "\3\3\1\104\6\3\1\104\12\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\5\3\1\235\26\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\11\3\1\146"+
    "\1\3\1\160\20\3\1\0\2\3\2\0\1\221\12\0"+
    "\1\221\14\0\1\221\13\0\1\221\1\0\2\221\15\0"+
    "\1\221\14\0\1\221\20\0\1\41\2\244\5\0\1\40"+
    "\1\0\3\244\2\41\1\244\1\41\1\244\2\41\1\244"+
    "\4\41\1\244\13\41\1\244\1\0\2\244\1\0\1\3"+
    "\2\245\5\0\1\40\1\0\3\245\2\3\1\245\1\3"+
    "\1\245\2\3\1\245\4\3\1\245\13\3\1\245\1\0"+
    "\2\245\1\0\3\3\5\0\1\40\1\0\12\3\1\44"+
    "\21\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\10\3\1\160\23\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\1\246\7\3\1\160\23\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\16\3\1\104\15\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\21\3"+
    "\1\160\12\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\17\3\1\247\13\3\1\235\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\20\3\1\250\13\3\1\0"+
    "\2\3\1\0\3\3\5\0\1\40\1\0\4\3\1\160"+
    "\27\3\1\0\2\3\1\0\3\3\5\0\1\40\1\0"+
    "\23\3\1\104\10\3\1\0\2\3\1\0\3\3\5\0"+
    "\1\40\1\0\4\3\1\251\27\3\1\0\2\3\1\0"+
    "\3\3\5\0\1\40\1\0\1\252\33\3\1\0\2\3"+
    "\1\0\1\41\2\253\5\0\1\40\1\0\3\253\2\41"+
    "\1\253\1\41\1\253\2\41\1\253\4\41\1\253\13\41"+
    "\1\253\1\0\2\253\1\0\1\3\2\254\5\0\1\40"+
    "\1\0\3\254\2\3\1\254\1\3\1\254\2\3\1\254"+
    "\4\3\1\254\13\3\1\254\1\0\2\254\1\0\3\3"+
    "\5\0\1\40\1\0\10\3\1\231\23\3\1\0\2\3"+
    "\1\0\3\3\5\0\1\40\1\0\2\3\1\235\31\3"+
    "\1\0\2\3\1\0\3\3\5\0\1\40\1\0\11\3"+
    "\1\202\22\3\1\0\2\3\1\0\3\3\5\0\1\40"+
    "\1\0\15\3\1\44\16\3\1\0\2\3\1\0\3\3"+
    "\5\0\1\40\1\0\10\3\1\255\23\3\1\0\2\3"+
    "\1\0\1\41\2\256\5\0\1\40\1\0\3\256\2\41"+
    "\1\256\1\41\1\256\2\41\1\256\4\41\1\256\13\41"+
    "\1\256\1\0\2\256\1\0\1\3\2\257\5\0\1\40"+
    "\1\0\3\257\2\3\1\257\1\3\1\257\2\3\1\257"+
    "\4\3\1\257\13\3\1\257\1\0\2\257\1\0\3\3"+
    "\5\0\1\40\1\0\10\3\1\104\23\3\1\0\2\3"+
    "\1\0\1\41\2\260\5\0\1\40\1\0\3\260\2\41"+
    "\1\260\1\41\1\260\2\41\1\260\4\41\1\260\13\41"+
    "\1\260\1\0\2\260\1\0\1\3\2\261\5\0\1\40"+
    "\1\0\3\261\2\3\1\261\1\3\1\261\2\3\1\261"+
    "\4\3\1\261\13\3\1\261\1\0\2\261";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6636];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\1\1\1\11\24\1\1\11"+
    "\2\0\3\1\2\11\77\1\2\0\50\1\1\11\22\1"+
    "\1\0\6\1\1\0\2\1\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */


	/**
	 * Constructor.  We must have this here as JFLex does not generate a
	 * no parameter constructor.
	 */
	public AssemblerTxTokenMaker() {
		super();
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 */
	public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
		super.addToken(array, start,end, tokenType, startOffset);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { ";", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *                    <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}

	/**
	 * Returns whether tokens of the specified type should have "mark
	 * occurrences" enabled for the current programming language.
	 * Basically, we return true for everything except blanks
	 *
	 * @param type The token type.
	 * @return Whether tokens of this type should have "mark occurrences"
	 *         enabled.
	 */
	public boolean getMarkOccurrencesOfTokenType(int type) {
        return     type == Token.IDENTIFIER
                || type == Token.FUNCTION
                || type == Token.RESERVED_WORD
                || type == Token.RESERVED_WORD_2
                || type == Token.DATA_TYPE
                || type == Token.LITERAL_CHAR
                || type == Token.LITERAL_NUMBER_HEXADECIMAL
                || type == Token.ANNOTATION
                || type == Token.OPERATOR
                || type == Token.VARIABLE;
	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 * @exception   IOException  if any I/O-Error occurs.
	 */
	private boolean zzRefill() throws java.io.IOException {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) throws java.io.IOException {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblerTxTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AssemblerTxTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { addToken(Token.RESERVED_WORD);
          }
        case 18: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 19: break;
        case 13: 
          { addToken(Token.FUNCTION);
          }
        case 20: break;
        case 11: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 21: break;
        case 4: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 22: break;
        case 15: 
          { addToken(Token.ANNOTATION);
          }
        case 23: break;
        case 10: 
          { addToken(Token.VARIABLE);
          }
        case 24: break;
        case 8: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 25: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 26: break;
        case 9: 
          { addToken(Token.PREPROCESSOR);
          }
        case 27: break;
        case 16: 
          { addToken(Token.DATA_TYPE);
          }
        case 28: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); /*addNullToken(); return firstToken;*/
          }
        case 29: break;
        case 17: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 30: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 31: break;
        case 12: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 32: break;
        case 2: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 33: break;
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 34: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 178: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
