/* The following code was generated by JFlex 1.4.3 on 9/04/12 17:23 */

/*
 * AssemblerFrTokenMaker.java - An object that can take a chunk of text and
 * return a linked list of tokens representing Fujitsu Fr assembler.
 * Based on AssemblerX86TokenMaker.java by Robert Futrell
 */
package com.nikonhacker.gui.component.sourceCode.syntaxHighlighter;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexTokenMaker;
import org.fife.ui.rsyntaxtextarea.DefaultToken;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMaker;

import javax.swing.text.Segment;
import java.io.IOException;


/**
 * This class takes plain text and returns tokens representing Fr
 * assembler.<p>
 *
 * This implementation was created using
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1; however, the generated file
 * was modified for performance.  Memory allocation needs to be almost
 * completely removed to be competitive with the handwritten lexers (subclasses
 * of <code>AbstractTokenMaker</code>, so this class has been modified so that
 * Strings are never allocated (via yytext()), and the scanner never has to
 * worry about refilling its buffer (needlessly copying chars around).
 * We can achieve this because RText always scans exactly 1 line of tokens at a
 * time, and hands the scanner this line as an array of characters (a Segment
 * really).  Since tokens contain pointers to char arrays instead of Strings
 * holding their contents, there is no need for allocating new memory for
 * Strings.<p>
 *
 * The actual algorithm generated for scanning has, of course, not been
 * modified.<p>
 *
 * If you wish to regenerate this file yourself, keep in mind the following:
 * <ul>
 *   <li>The generated AssemblerFrTokenMaker.java</code> file will contain two
 *       definitions of both <code>zzRefill</code> and <code>yyreset</code>.
 *       You should hand-delete the second of each definition (the ones
 *       generated by the lexer), as these generated methods modify the input
 *       buffer, which we'll never have to do.</li>
 *   <li>You should also change the declaration/definition of zzBuffer to NOT
 *       be initialized.  This is a needless memory allocation for us since we
 *       will be pointing the array somewhere else anyway.</li>
 *   <li>You should NOT call <code>yylex()</code> on the generated scanner
 *       directly; rather, you should use <code>getTokenList</code> as you would
 *       with any other <code>TokenMaker</code> instance.</li>
 * </ul>
 *
 * @author Robert Futrell
 * @version 0.2
 *
 */

public class AssemblerFrTokenMaker extends AbstractJFlexTokenMaker implements TokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\10\1\0\1\11\23\0\1\11\1\14\1\5\2\0"+
    "\1\13\1\14\1\6\2\0\1\13\1\13\1\4\1\13\1\4\1\13"+
    "\1\36\1\40\1\17\1\41\1\42\1\52\1\2\1\2\1\44\1\2"+
    "\1\12\1\7\1\14\1\14\1\14\2\0\1\15\1\24\1\20\1\16"+
    "\1\30\1\3\1\46\1\26\1\35\1\47\1\1\1\27\1\33\1\21"+
    "\1\31\1\23\1\45\1\25\1\22\1\32\1\37\1\34\1\50\1\43"+
    "\1\51\1\1\1\4\1\0\1\4\1\14\1\1\1\0\1\15\1\24"+
    "\1\20\1\16\1\30\1\3\1\46\1\26\1\35\1\47\1\1\1\27"+
    "\1\33\1\21\1\31\1\23\1\45\1\25\1\22\1\32\1\37\1\34"+
    "\1\50\1\43\1\51\1\1\1\0\1\14\1\0\1\14\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\4\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\23\1\1\0\1\10\3\0\1\11\1\0\1\12\1\13"+
    "\1\0\1\11\2\0\1\14\1\0\1\14\2\0\1\14"+
    "\11\0\1\15\3\0\3\16\11\0\1\11\1\15\5\0"+
    "\1\15\1\0\1\11\7\0\2\1\1\10\1\0\2\1"+
    "\2\15\5\1\1\15\6\1\1\15\1\1\1\10\5\1"+
    "\1\16\3\1\1\15\2\1\2\15\2\1\2\17\1\15"+
    "\1\1\1\15\5\1\1\16\1\20\1\1\1\16\1\10"+
    "\2\1\1\15\1\0\4\1\1\15\1\0\1\1\1\0"+
    "\1\1\2\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\53\0\u0158\0\53\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f"+
    "\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387"+
    "\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\53"+
    "\0\u04df\0\u050a\0\u0535\0\u04b4\0\u0560\0\53\0\53\0\u058b"+
    "\0\u0535\0\u05b6\0\u05e1\0\u0535\0\u060c\0\u04b4\0\u0637\0\u0662"+
    "\0\u0560\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f"+
    "\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7"+
    "\0\u0912\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f"+
    "\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97"+
    "\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef"+
    "\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u04b4\0\u0d9b\0\u0dc6\0\u0df1"+
    "\0\u0d70\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e"+
    "\0\u04b4\0\u0560\0\u0a6a\0\u0f49\0\u0f74\0\u0f9f\0\u0fca\0\u0ff5"+
    "\0\u1020\0\u104b\0\u09e9\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\u1122"+
    "\0\u114d\0\u1178\0\u11a3\0\u0fca\0\u11ce\0\u11f9\0\u1224\0\u124f"+
    "\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u12fb\0\u0739\0\u127a\0\u1326"+
    "\0\u1351\0\u137c\0\u13a7\0\u13d2\0\u0d9b\0\u04b4\0\u13fd\0\u04b4"+
    "\0\u1428\0\u124f\0\u1453\0\u0e72\0\u147e\0\u14a9\0\u14d4\0\u14ff"+
    "\0\u152a\0\u0d9b\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u04df\0\u04b4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\2\2\13\1\14\1\15\1\4\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\3\1\24\1\25"+
    "\1\26\1\27\1\30\1\3\1\31\1\4\1\32\3\4"+
    "\1\33\1\4\1\34\1\3\1\35\1\36\1\3\1\4"+
    "\54\0\3\37\6\0\1\40\2\0\36\37\1\0\1\41"+
    "\2\42\6\0\1\40\2\0\4\42\3\41\1\42\3\41"+
    "\1\42\5\41\1\42\1\41\3\42\1\41\1\42\5\41"+
    "\1\42\1\0\1\37\2\43\6\0\1\40\2\0\4\43"+
    "\2\37\1\44\1\43\3\37\1\43\5\37\1\43\1\37"+
    "\3\43\1\37\1\43\3\37\1\45\1\37\1\43\5\6"+
    "\1\46\45\6\6\7\1\47\44\7\10\10\1\0\42\10"+
    "\11\0\1\12\42\0\1\37\2\43\6\0\1\40\2\0"+
    "\1\43\1\50\1\43\1\51\1\52\1\53\1\37\1\43"+
    "\3\37\1\43\5\37\1\43\1\37\3\43\1\37\1\43"+
    "\5\37\1\43\1\0\1\37\1\43\1\54\6\0\1\40"+
    "\2\0\1\43\1\54\2\43\3\37\1\54\3\37\1\43"+
    "\1\55\1\56\1\57\1\37\1\60\1\43\1\37\3\43"+
    "\1\37\1\43\1\56\2\37\1\61\1\37\1\43\1\0"+
    "\1\37\2\43\6\0\1\40\2\0\1\62\2\43\1\63"+
    "\3\37\1\43\3\37\1\43\1\64\1\37\1\65\2\37"+
    "\1\43\1\37\3\43\1\37\1\43\5\37\1\43\1\0"+
    "\3\37\6\0\1\40\2\0\14\37\1\66\21\37\1\0"+
    "\3\37\6\0\1\40\2\0\1\37\1\67\1\37\1\70"+
    "\1\37\1\71\1\44\1\72\5\37\1\73\4\37\1\74"+
    "\10\37\1\45\2\37\1\0\3\37\6\0\1\40\2\0"+
    "\3\37\1\44\1\37\1\44\6\37\1\66\5\37\1\75"+
    "\13\37\1\0\1\37\2\43\6\0\1\40\2\0\1\76"+
    "\2\43\1\77\1\100\1\37\1\101\1\43\1\102\1\103"+
    "\1\104\1\105\1\106\1\107\1\37\1\101\1\37\1\43"+
    "\1\37\3\43\1\37\1\43\1\37\1\110\2\37\1\111"+
    "\1\43\1\0\1\37\1\44\1\37\6\0\1\40\2\0"+
    "\2\37\1\44\3\37\1\44\4\37\1\112\5\37\1\44"+
    "\1\37\1\113\2\44\1\37\1\44\5\37\1\44\1\0"+
    "\3\37\6\0\1\40\2\0\1\37\1\114\3\37\1\115"+
    "\5\37\1\116\22\37\1\0\1\37\2\43\6\0\1\40"+
    "\2\0\4\43\1\117\2\37\1\43\3\37\1\43\1\120"+
    "\4\37\1\43\1\37\3\43\1\121\1\43\5\37\1\43"+
    "\1\0\3\37\6\0\1\40\2\0\10\37\1\122\25\37"+
    "\1\0\3\37\6\0\1\40\2\0\7\37\1\123\23\37"+
    "\1\45\2\37\1\0\3\37\6\0\1\40\2\0\1\37"+
    "\1\124\12\37\1\125\5\37\1\126\13\37\1\0\3\37"+
    "\6\0\1\40\2\0\4\37\1\127\5\37\1\130\23\37"+
    "\1\0\3\37\6\0\1\40\2\0\5\37\1\71\30\37"+
    "\1\0\3\37\6\0\1\40\2\0\3\37\1\131\32\37"+
    "\1\0\3\37\6\0\1\40\2\0\33\37\1\45\2\37"+
    "\1\0\3\37\6\0\1\40\2\0\16\37\1\132\17\37"+
    "\1\0\3\37\6\0\1\40\2\0\14\37\1\133\21\37"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\36\135\1\0\3\41\6\0\1\40\2\0\36\41\1\0"+
    "\1\41\2\137\6\0\1\40\2\0\4\137\3\41\1\137"+
    "\3\41\1\137\5\41\1\137\1\41\3\137\1\41\1\137"+
    "\5\41\1\137\1\134\1\135\2\140\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\4\140\3\135\1\140\3\135\1\140"+
    "\5\135\1\140\1\135\3\140\1\135\1\140\5\135\1\140"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\14\135\1\141\21\135\1\134\1\135\2\140\1\0\3\134"+
    "\2\0\1\136\1\0\1\134\1\140\1\142\2\140\3\135"+
    "\1\140\3\135\1\140\5\135\1\140\1\135\3\140\1\135"+
    "\1\140\5\135\1\140\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\1\135\1\122\34\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\10\135\1\143"+
    "\25\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\17\135\1\144\16\135\1\134\3\135\1\0\3\134"+
    "\2\0\1\136\1\0\1\134\14\135\1\145\21\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\17\135"+
    "\1\146\16\135\1\134\1\135\2\140\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\4\140\3\135\1\140\2\135\1\147"+
    "\1\140\5\135\1\140\1\135\3\140\1\135\1\140\5\135"+
    "\1\140\1\134\1\135\2\140\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\4\140\3\135\1\140\1\44\2\135\1\140"+
    "\5\135\1\140\1\135\3\140\1\135\1\140\5\135\1\140"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\6\135\1\150\27\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\6\135\1\143\27\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\6\135\1\151"+
    "\27\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\33\135\1\152\2\135\1\134\3\135\1\0\3\134"+
    "\2\0\1\136\1\0\1\134\10\135\1\44\25\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\6\135"+
    "\1\44\27\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\34\135\1\153\1\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\7\135\1\151\1\154"+
    "\1\151\4\135\1\155\1\135\1\156\1\135\1\157\13\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\7\135\1\160\26\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\5\135\1\144\30\135\1\134\1\135"+
    "\2\140\1\0\3\134\2\0\1\136\1\0\1\134\4\140"+
    "\1\161\2\135\1\140\3\135\1\140\5\135\1\140\1\135"+
    "\3\140\1\135\1\140\5\135\1\140\1\134\1\135\2\140"+
    "\1\0\3\134\2\0\1\162\1\0\1\134\4\140\3\135"+
    "\1\140\3\135\1\140\5\135\1\140\1\135\3\140\1\135"+
    "\1\140\5\135\1\140\1\134\3\135\1\0\3\134\2\0"+
    "\1\162\1\0\1\134\3\135\1\101\7\135\2\101\2\135"+
    "\1\101\16\135\1\134\3\135\1\0\3\134\2\0\1\162"+
    "\1\0\1\134\36\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\1\101\35\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\20\135\1\101\15\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\5\135\1\101\5\135\1\101\1\135\1\101\20\135\1\134"+
    "\1\135\2\140\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\4\140\3\135\1\140\3\135\1\140\1\163\4\135\1\140"+
    "\1\135\3\140\1\135\1\140\1\101\4\135\1\140\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\10\135"+
    "\1\164\25\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\5\135\1\165\30\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\13\135\1\101\1\135"+
    "\1\101\20\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\15\135\1\166\20\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\1\167\14\135\1\170"+
    "\20\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\2\135\1\44\16\135\1\44\1\135\3\44\7\135"+
    "\1\44\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\10\135\1\154\5\135\1\155\1\135\1\171\1\135"+
    "\1\157\13\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\10\135\1\143\1\135\1\143\23\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\1\172"+
    "\35\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\15\135\1\173\20\135\1\134\3\135\1\0\3\134"+
    "\2\0\1\136\1\0\1\134\10\135\1\174\25\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\15\135"+
    "\1\175\20\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\3\135\1\176\3\135\1\151\1\135\1\151"+
    "\24\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\10\135\1\44\23\135\1\153\1\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\11\135\2\44"+
    "\23\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\17\135\1\151\16\135\1\134\3\135\1\0\3\134"+
    "\2\0\1\136\1\0\1\134\12\135\1\177\23\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\15\135"+
    "\1\200\20\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\16\135\1\44\17\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\11\135\1\201\24\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\6\135\1\101\27\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\10\135\1\202\25\135\4\134\1\0"+
    "\3\134\2\0\1\134\1\0\37\134\1\0\1\41\2\203"+
    "\6\0\1\40\2\0\4\203\3\41\1\203\3\41\1\203"+
    "\5\41\1\203\1\41\3\203\1\41\1\203\5\41\1\203"+
    "\1\134\1\135\2\204\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\4\204\3\135\1\204\3\135\1\204\5\135\1\204"+
    "\1\135\3\204\1\135\1\204\5\135\1\204\1\134\1\135"+
    "\2\204\1\0\3\134\2\0\1\136\1\0\1\134\2\204"+
    "\2\205\1\143\1\206\1\135\1\204\3\135\1\204\5\135"+
    "\1\204\1\135\3\204\1\135\1\204\5\135\1\204\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\2\135"+
    "\1\151\33\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\11\135\1\151\24\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\17\135\1\207\16\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\2\135\1\151\16\135\1\210\1\135\2\151\1\211\10\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\12\135\1\101\23\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\5\135\1\212\4\135\1\213\1\135"+
    "\1\206\21\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\13\135\1\211\22\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\21\135\1\151\1\135"+
    "\1\151\12\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\12\135\1\214\23\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\7\135\1\151\1\135"+
    "\1\151\24\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\3\135\2\151\31\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\1\135\1\164\34\135"+
    "\4\134\1\0\3\134\2\0\1\134\1\0\2\134\1\215"+
    "\35\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\11\135\2\151\23\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\15\135\1\164\20\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\13\135\1\216"+
    "\22\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\12\135\1\217\23\135\1\134\3\135\1\0\3\134"+
    "\2\0\1\162\1\0\1\134\20\135\1\220\15\135\1\134"+
    "\3\135\1\0\3\134\2\0\1\221\1\0\1\134\36\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\17\135\1\222\16\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\13\135\1\223\22\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\5\135\1\157"+
    "\14\135\1\157\13\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\3\135\1\223\32\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\11\135\1\151"+
    "\10\135\1\224\13\135\1\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\13\135\1\151\22\135\1\134\3\135"+
    "\1\0\3\134\2\0\1\136\1\0\1\134\7\135\1\151"+
    "\26\135\1\134\3\135\1\0\3\134\2\0\1\136\1\0"+
    "\1\134\1\135\1\216\34\135\1\0\1\41\2\225\6\0"+
    "\1\40\2\0\4\225\3\41\1\225\3\41\1\225\5\41"+
    "\1\225\1\41\3\225\1\41\1\225\5\41\1\225\1\134"+
    "\1\135\2\226\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\4\226\3\135\1\226\3\135\1\226\5\135\1\226\1\135"+
    "\3\226\1\135\1\226\5\135\1\226\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\5\135\1\151\14\135"+
    "\1\151\13\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\5\135\1\151\30\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\15\135\1\151\1\135"+
    "\1\151\16\135\1\134\3\135\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\1\135\1\151\34\135\1\134\3\135\1\0"+
    "\3\134\2\0\1\136\1\0\1\134\16\135\1\151\17\135"+
    "\1\134\3\135\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\23\135\1\227\1\135\1\216\1\135\1\216\6\135\4\134"+
    "\1\0\3\134\2\0\1\134\1\0\3\134\1\230\21\134"+
    "\1\231\2\134\1\232\7\134\3\135\1\0\3\134\2\0"+
    "\1\136\1\0\1\134\10\135\1\151\25\135\1\0\1\41"+
    "\2\233\6\0\1\40\2\0\4\233\3\41\1\233\3\41"+
    "\1\233\5\41\1\233\1\41\3\233\1\41\1\233\5\41"+
    "\1\233\1\134\1\135\2\234\1\0\3\134\2\0\1\136"+
    "\1\0\1\134\4\234\3\135\1\234\3\135\1\234\5\135"+
    "\1\234\1\135\3\234\1\135\1\234\5\135\1\234\1\134"+
    "\3\135\1\0\3\134\2\0\1\136\1\0\1\134\21\135"+
    "\1\216\14\135\4\134\1\0\3\134\2\0\1\134\1\0"+
    "\22\134\1\232\20\134\1\0\3\134\2\0\1\134\1\0"+
    "\3\134\1\232\33\134\1\0\1\41\2\235\6\0\1\40"+
    "\2\0\4\235\3\41\1\235\3\41\1\235\5\41\1\235"+
    "\1\41\3\235\1\41\1\235\5\41\1\235\1\134\1\135"+
    "\2\236\1\0\3\134\2\0\1\136\1\0\1\134\4\236"+
    "\3\135\1\236\3\135\1\236\5\135\1\236\1\135\3\236"+
    "\1\135\1\236\5\135\1\236\1\0\1\41\2\237\6\0"+
    "\1\40\2\0\4\237\3\41\1\237\3\41\1\237\5\41"+
    "\1\237\1\41\3\237\1\41\1\237\5\41\1\237\1\134"+
    "\1\135\2\240\1\0\3\134\2\0\1\136\1\0\1\134"+
    "\4\240\3\135\1\240\3\135\1\240\5\135\1\240\1\135"+
    "\3\240\1\135\1\240\5\135\1\240";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5633];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\1\1\1\11\23\1\1\0"+
    "\1\11\3\0\1\1\1\0\2\11\1\0\1\1\2\0"+
    "\1\1\1\0\1\1\2\0\1\1\11\0\1\1\3\0"+
    "\3\1\11\0\2\1\5\0\1\1\1\0\1\1\7\0"+
    "\3\1\1\0\65\1\1\0\5\1\1\0\1\1\1\0"+
    "\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */


	/**
	 * Constructor.  We must have this here as JFLex does not generate a
	 * no parameter constructor.
	 */
	public AssemblerFrTokenMaker() {
		super();
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 */
	public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
		super.addToken(array, start,end, tokenType, startOffset);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { ";", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *                    <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}

	/**
	 * Returns whether tokens of the specified type should have "mark
	 * occurrences" enabled for the current programming language.
	 * Basically, we return true for everything except blanks
	 *
	 * @param type The token type.
	 * @return Whether tokens of this type should have "mark occurrences"
	 *         enabled.
	 */
	public boolean getMarkOccurrencesOfTokenType(int type) {
        return     type == Token.IDENTIFIER
                || type == Token.FUNCTION
                || type == Token.RESERVED_WORD
                || type == Token.RESERVED_WORD_2
                || type == Token.DATA_TYPE
                || type == Token.LITERAL_CHAR
                || type == Token.LITERAL_NUMBER_HEXADECIMAL
                || type == Token.ANNOTATION
                || type == Token.OPERATOR
                || type == Token.VARIABLE;
	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 * @exception   IOException  if any I/O-Error occurs.
	 */
	private boolean zzRefill() throws java.io.IOException {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) throws java.io.IOException {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblerFrTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AssemblerFrTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { addToken(Token.RESERVED_WORD);
          }
        case 18: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 19: break;
        case 12: 
          { addToken(Token.FUNCTION);
          }
        case 20: break;
        case 10: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 21: break;
        case 4: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 22: break;
        case 15: 
          { addToken(Token.ANNOTATION);
          }
        case 23: break;
        case 14: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 24: break;
        case 9: 
          { addToken(Token.VARIABLE);
          }
        case 25: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 26: break;
        case 8: 
          { addToken(Token.PREPROCESSOR);
          }
        case 27: break;
        case 16: 
          { addToken(Token.DATA_TYPE);
          }
        case 28: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); /*addNullToken(); return firstToken;*/
          }
        case 29: break;
        case 17: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 30: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 31: break;
        case 11: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 32: break;
        case 2: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 33: break;
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 34: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 161: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
