/* The following code was generated by JFlex 1.4.1 on 2/28/12 7:53 PM */

/*
 * Generated on 2/28/12 7:53 PM
 */
package com.nikonhacker.gui.component.sourceCode;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexCTokenMaker;
import org.fife.ui.rsyntaxtextarea.DefaultToken;
import org.fife.ui.rsyntaxtextarea.Token;

import javax.swing.text.Segment;
import java.io.IOException;


/**
 * AssemblerFrTokenMaker.java - An object that can take a chunk of text and
return a linked list of tokens representing Fujitsu Fr assembler.
Generated by TokenMakerMaker
 */

public class AssemblerFrTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 1;
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\10\1\0\1\16\1\13\22\0\1\16\1\7\1\13"+
    "\1\15\1\1\1\7\1\7\1\7\1\35\1\35\1\7\1\36\1\7"+
    "\1\25\1\26\1\37\1\4\1\67\1\47\1\14\1\70\1\75\1\6"+
    "\1\6\1\73\1\3\1\43\1\17\1\13\1\7\1\13\1\7\1\34"+
    "\1\45\1\54\1\50\1\46\1\24\1\74\1\61\1\56\1\63\1\72"+
    "\1\1\1\21\1\65\1\51\1\57\1\53\1\60\1\55\1\52\1\62"+
    "\1\66\1\64\1\1\1\71\2\1\1\35\1\11\1\35\1\13\1\2"+
    "\1\0\1\5\1\5\1\5\1\22\1\30\1\23\1\1\1\40\1\42"+
    "\2\1\1\31\1\1\1\1\1\1\1\41\1\1\1\1\1\32\1\27"+
    "\1\12\1\1\1\44\1\20\2\1\1\33\1\13\1\33\1\7\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\2\2\1\3\1\4\1\5\3\1\1\6"+
    "\1\7\20\1\1\10\1\11\3\10\1\0\1\12\1\2"+
    "\1\13\1\12\1\13\1\12\1\14\1\12\1\1\1\15"+
    "\5\1\1\16\12\1\1\15\5\1\2\15\6\1\1\16"+
    "\1\15\2\1\1\16\4\1\5\0\1\13\1\0\2\14"+
    "\5\1\1\15\1\1\1\15\1\1\1\15\5\1\1\15"+
    "\1\1\1\15\1\1\1\0\2\1\1\15\1\1\2\15"+
    "\1\1\5\0\2\1\1\0\2\1\1\15\3\1\2\15"+
    "\2\0\1\17\6\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\174\0\u0174"+
    "\0\174\0\u01b2\0\u01f0\0\u022e\0\174\0\174\0\u026c\0\u02aa"+
    "\0\u02e8\0\u0326\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a"+
    "\0\u04d8\0\u0516\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\174"+
    "\0\u068a\0\u06c8\0\u0706\0\u0744\0\u0782\0\u0782\0\u0782\0\u07c0"+
    "\0\u07fe\0\u083c\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972\0\u09b0"+
    "\0\u09ee\0\u0a2c\0\u0a6a\0\272\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62"+
    "\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14\0\u0d52"+
    "\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42"+
    "\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132"+
    "\0\u1170\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322"+
    "\0\u1360\0\u139e\0\u13dc\0\u141a\0\u0782\0\u1458\0\u1496\0\u14d4"+
    "\0\u1512\0\u1550\0\u158e\0\u15cc\0\u160a\0\u158e\0\u1648\0\u1686"+
    "\0\u16c4\0\u1702\0\u1740\0\u177e\0\u17bc\0\272\0\u17fa\0\u1838"+
    "\0\u1876\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea\0\u1a28"+
    "\0\u1a66\0\u1aa4\0\u1ae2\0\u1b20\0\u1b5e\0\u1b9c\0\u19ea\0\u1bda"+
    "\0\u1c18\0\u1c56\0\u1c94\0\u1a66\0\u1cd2\0\u1d10\0\u1d4e\0\174"+
    "\0\u16c4\0\u1d8c\0\u1dca\0\u1e08\0\u1e46\0\u1e84\0\u1ec2\0\u1f00"+
    "\0\u1e08\0\u1f3e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\4\1\5\1\3\1\7"+
    "\1\3\1\4\1\3\1\5\1\3\1\10\1\11\1\4"+
    "\1\12\2\4\1\13\1\3\1\14\4\4\1\15\1\16"+
    "\1\15\1\16\1\3\3\4\1\3\1\4\1\17\1\20"+
    "\1\5\1\21\1\22\1\23\1\24\1\25\1\26\1\4"+
    "\1\27\2\4\1\30\1\31\1\4\1\32\1\33\2\5"+
    "\1\34\1\35\1\5\1\36\1\5\10\37\1\40\12\37"+
    "\1\41\14\37\1\42\3\37\1\43\31\37\77\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\32\4\3\45\2\5\1\45"+
    "\1\5\2\0\2\45\1\0\1\5\1\45\2\0\1\45"+
    "\1\46\2\47\1\50\1\0\1\51\1\45\1\50\1\46"+
    "\1\45\1\0\1\45\3\0\3\45\1\0\2\45\1\47"+
    "\1\5\17\45\2\5\2\45\1\5\1\47\1\5\3\45"+
    "\1\52\1\53\1\45\1\53\2\0\2\45\1\0\1\53"+
    "\1\45\2\0\1\54\1\46\2\47\1\50\1\0\1\51"+
    "\1\45\1\50\1\46\1\45\1\0\1\45\3\0\3\45"+
    "\1\0\2\45\1\47\1\53\17\45\2\53\1\54\1\45"+
    "\1\52\1\47\1\53\16\0\1\10\60\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\4\4\1\55\2\0"+
    "\4\4\5\0\3\4\1\0\2\4\1\56\3\4\1\57"+
    "\23\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\5\4"+
    "\1\60\5\4\1\61\11\4\1\62\4\4\3\0\2\51"+
    "\1\0\1\51\5\0\1\51\32\0\1\51\17\0\2\51"+
    "\2\0\1\51\1\0\1\51\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\2\4\1\63\1\4\1\64\1\65\1\66"+
    "\23\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\13\4"+
    "\1\67\3\4\1\70\1\4\1\71\10\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\1\4\1\72\2\4\1\73"+
    "\6\4\1\74\5\4\1\75\10\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\13\4\1\76\16\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\4\4\1\73\1\4\1\36"+
    "\1\64\6\4\1\77\3\4\1\100\7\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\4\4\1\64\1\4\1\64"+
    "\4\4\1\76\6\4\1\101\7\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\1\4\1\102\2\4"+
    "\1\103\2\0\4\4\5\0\3\4\1\0\1\4\1\104"+
    "\2\4\1\105\1\106\1\4\1\105\1\4\1\107\1\110"+
    "\1\111\1\4\1\112\1\113\1\4\1\105\11\4\1\0"+
    "\2\4\2\64\1\4\1\64\2\0\1\44\1\4\1\0"+
    "\1\64\3\0\4\4\1\114\2\0\4\4\5\0\3\4"+
    "\1\0\3\4\1\64\3\4\1\64\13\4\1\115\1\64"+
    "\2\4\1\64\1\4\1\64\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\11\4\1\116\20\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\10\4\1\73\21\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\1\4\1\117"+
    "\3\4\2\0\4\4\5\0\3\4\1\0\5\4\1\120"+
    "\24\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\2\4"+
    "\1\121\10\4\1\122\6\4\1\123\7\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\6\4\1\36\23\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\4\4\1\124\25\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\21\4\1\125"+
    "\10\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\7\4"+
    "\1\64\22\4\10\37\1\0\12\37\1\0\14\37\1\0"+
    "\3\37\1\0\31\37\27\0\1\126\12\0\1\127\62\0"+
    "\1\130\112\0\1\131\43\0\1\132\63\0\7\45\2\0"+
    "\2\45\1\0\2\45\2\0\5\45\2\0\4\45\1\0"+
    "\1\45\3\0\3\45\1\0\35\45\2\133\1\45\1\133"+
    "\2\0\2\45\1\0\1\133\1\45\2\0\5\45\1\134"+
    "\1\0\4\45\1\0\1\45\1\0\1\134\1\0\3\45"+
    "\1\0\3\45\1\133\17\45\2\133\2\45\1\133\1\45"+
    "\1\133\3\45\2\51\1\45\1\51\2\0\2\45\1\0"+
    "\1\51\1\45\2\0\2\45\2\47\1\50\2\0\1\45"+
    "\1\50\2\45\1\0\1\45\3\0\3\45\1\0\2\45"+
    "\1\47\1\51\17\45\2\51\2\45\1\51\1\47\1\51"+
    "\3\45\2\52\1\45\1\52\2\0\2\45\1\0\1\52"+
    "\1\45\2\0\2\45\2\47\1\50\1\0\1\51\1\45"+
    "\1\50\2\45\1\0\1\45\3\0\3\45\1\0\2\45"+
    "\1\47\1\52\17\45\2\52\2\45\1\52\1\47\1\52"+
    "\3\45\1\52\1\53\1\45\1\53\2\0\2\45\1\0"+
    "\1\53\1\45\2\0\1\45\1\135\2\47\1\50\1\0"+
    "\1\51\1\45\1\50\1\135\1\45\1\0\1\45\3\0"+
    "\3\45\1\0\2\45\1\47\1\53\17\45\2\53\2\45"+
    "\1\52\1\47\1\53\3\45\4\136\2\0\2\45\1\0"+
    "\1\136\1\45\2\0\2\45\3\136\2\0\1\45\1\136"+
    "\2\45\1\0\1\45\3\0\3\45\1\0\1\45\4\136"+
    "\3\45\1\136\12\45\2\136\2\45\3\136\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\1\4\1\137\30\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\11\4\1\140\5\4"+
    "\1\141\1\4\1\142\1\143\7\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\1\4\1\144\3\4"+
    "\2\0\4\4\5\0\3\4\1\0\11\4\1\144\20\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\16\4\1\145"+
    "\13\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\11\4"+
    "\1\146\20\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\0"+
    "\16\4\1\147\13\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\2\4\1\150\27\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\2\4\1\116\27\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\11\4\1\144\20\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\20\4\1\151\11\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\20\4\1\152\11\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\13\4\1\153"+
    "\16\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\1\4\1\154\3\4\2\0\4\4\5\0\3\4"+
    "\1\0\32\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\0"+
    "\11\4\1\64\20\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\7\4\1\155\22\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\7\4\1\144\22\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\7\4\1\156\22\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\10\4\1\156\1\140\1\156"+
    "\4\4\1\157\1\4\1\142\10\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\10\4\1\160\21\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\6\4\1\151\23\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\4\4"+
    "\1\105\2\0\4\4\5\0\3\4\1\0\6\4\1\105"+
    "\7\4\1\105\13\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\13\4\1\111\1\105\15\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\5\4\1\161\24\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\162\32\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\4\4\1\105\2\0"+
    "\4\4\5\0\3\4\1\162\4\4\1\105\6\4\1\105"+
    "\4\4\1\105\11\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\1\4\1\105\30\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\17\4\1\105\12\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\11\4\1\163\20\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\4\4\1\105"+
    "\2\0\4\4\5\0\3\4\1\0\16\4\1\105\13\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\6\4\1\164"+
    "\23\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\16\4"+
    "\1\165\13\4\1\0\3\4\1\64\2\4\2\0\1\44"+
    "\1\4\1\0\1\64\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\3\4\1\64\17\4\2\64\4\4\1\64"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\4\4\1\166"+
    "\3\4\1\156\1\4\1\156\17\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\21\4\1\64\10\4\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\16\4\1\167\13\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\1\4"+
    "\1\64\3\4\2\0\4\4\5\0\3\4\1\0\12\4"+
    "\1\64\17\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\0"+
    "\20\4\1\156\11\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\1\4\1\170\3\4\2\0\4\4"+
    "\5\0\3\4\1\0\32\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\12\4\1\171\17\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\7\4\1\105\22\4\41\0\1\172"+
    "\65\0\1\173\73\0\1\174\112\0\1\175\34\0\4\176"+
    "\5\0\1\176\5\0\3\176\3\0\1\176\14\0\4\176"+
    "\3\0\1\176\12\0\2\176\2\0\3\176\3\45\2\133"+
    "\1\45\1\133\2\0\2\45\1\0\1\133\1\45\2\0"+
    "\2\45\2\47\1\45\2\0\4\45\1\0\1\45\3\0"+
    "\3\45\1\0\2\45\1\47\1\133\17\45\2\133\2\45"+
    "\1\133\1\47\1\133\3\0\2\133\1\0\1\133\5\0"+
    "\1\133\32\0\1\133\17\0\2\133\2\0\1\133\1\0"+
    "\1\133\3\45\4\136\2\0\2\45\1\0\1\136\1\45"+
    "\2\0\1\45\1\135\3\136\2\0\1\45\1\136\1\135"+
    "\1\45\1\0\1\45\3\0\3\45\1\0\1\45\4\136"+
    "\3\45\1\136\12\45\2\136\2\45\3\136\1\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\20\4\1\177\11\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\4\4"+
    "\1\200\2\0\4\4\5\0\3\4\1\0\32\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\201\32\4\1\0\3\4"+
    "\1\156\2\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\23\4\1\156"+
    "\6\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\10\4"+
    "\1\156\1\4\1\156\17\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\3\4\1\156\26\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\4\4\1\202\2\0"+
    "\4\4\5\0\3\4\1\0\32\4\1\0\6\4\2\0"+
    "\1\44\1\4\1\0\1\4\3\0\5\4\2\0\4\4"+
    "\5\0\3\4\1\0\6\4\1\143\13\4\1\143\7\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\3\4\2\156"+
    "\1\144\1\76\23\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\12\4\1\156\17\4\1\0\3\4\1\203\2\4"+
    "\2\0\1\44\1\4\1\0\1\156\3\0\5\4\2\0"+
    "\4\4\5\0\3\4\1\0\3\4\1\156\17\4\1\156"+
    "\1\200\5\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\0"+
    "\20\4\1\204\11\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\1\4\1\105\3\4\2\0\4\4"+
    "\5\0\3\4\1\0\32\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\1\4\1\205\3\4\2\0"+
    "\4\4\5\0\3\4\1\0\6\4\1\206\4\4\1\76"+
    "\16\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\1\4\1\207\3\4\2\0\4\4\5\0\3\4"+
    "\1\0\32\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\0"+
    "\4\4\2\156\24\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\2\4\1\163\27\4\46\0\1\210\30\0\6\4"+
    "\2\0\1\44\1\4\1\0\1\4\3\0\1\4\1\156"+
    "\3\4\2\0\4\4\5\0\3\4\1\0\12\4\1\156"+
    "\17\4\1\0\6\4\2\0\1\44\1\4\1\0\1\4"+
    "\3\0\5\4\2\0\4\4\5\0\3\4\1\0\16\4"+
    "\1\163\13\4\1\0\6\4\2\0\1\44\1\4\1\0"+
    "\1\4\3\0\5\4\2\0\4\4\5\0\3\4\1\162"+
    "\17\4\1\156\12\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\4\4\1\202\25\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\4\4\1\156\2\0\4\4"+
    "\5\0\3\4\1\0\32\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\12\4\1\156\7\4\1\211\7\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\10\4\1\156\21\4"+
    "\43\0\1\212\62\0\1\172\106\0\1\213\62\0\1\214"+
    "\52\0\4\215\5\0\1\215\5\0\3\215\3\0\1\215"+
    "\14\0\4\215\3\0\1\215\12\0\2\215\2\0\3\215"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\6\4\1\156"+
    "\23\4\14\0\1\216\32\0\1\217\23\0\1\210\3\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\11\4\1\156\20\4"+
    "\1\0\6\4\2\0\1\44\1\4\1\0\1\4\3\0"+
    "\5\4\2\0\4\4\5\0\3\4\1\0\6\4\1\156"+
    "\13\4\1\156\7\4\1\0\6\4\2\0\1\44\1\4"+
    "\1\0\1\4\3\0\5\4\2\0\4\4\5\0\3\4"+
    "\1\0\2\4\1\156\27\4\1\0\6\4\2\0\1\44"+
    "\1\4\1\0\1\4\3\0\5\4\2\0\4\4\5\0"+
    "\3\4\1\0\16\4\1\156\1\4\1\156\11\4\1\0"+
    "\6\4\2\0\1\44\1\4\1\0\1\4\3\0\5\4"+
    "\2\0\4\4\5\0\3\4\1\0\21\4\1\156\10\4"+
    "\37\0\1\220\70\0\1\172\10\0\1\212\33\0\1\214"+
    "\1\221\4\214\1\221\2\0\1\214\1\0\1\214\1\221"+
    "\1\0\1\221\5\214\2\221\4\214\1\0\3\221\4\214"+
    "\1\221\32\214\3\0\4\222\5\0\1\222\5\0\3\222"+
    "\3\0\1\222\14\0\4\222\3\0\1\222\12\0\2\222"+
    "\2\0\3\222\47\0\1\210\32\0\1\210\130\0\1\214"+
    "\41\0\4\4\5\0\1\4\5\0\3\4\3\0\1\4"+
    "\14\0\4\4\3\0\1\4\12\0\2\4\2\0\3\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8060];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\1\1\1\11\3\1\2\11"+
    "\21\1\1\11\3\1\1\0\61\1\5\0\1\1\1\0"+
    "\25\1\1\0\7\1\5\0\2\1\1\0\6\1\1\11"+
    "\1\1\2\0\1\1\6\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public AssemblerFrTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return null;
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			/* No multi-line comments */
			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblerFrTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AssemblerFrTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { addToken(Token.RESERVED_WORD);
          }
        case 16: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 17: break;
        case 11: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 18: break;
        case 4: 
          { addToken(Token.WHITESPACE);
          }
        case 19: break;
        case 15: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 20: break;
        case 14: 
          { addToken(Token.DATA_TYPE);
          }
        case 21: break;
        case 10: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 22: break;
        case 5: 
          { start = zzMarkedPos-1; yybegin(EOL_COMMENT);
          }
        case 23: break;
        case 12: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 24: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 25: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 26: break;
        case 3: 
          { addNullToken(); return firstToken;
          }
        case 27: break;
        case 9: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 28: break;
        case 8: 
          { 
          }
        case 29: break;
        case 6: 
          { addToken(Token.SEPARATOR);
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 147: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 148: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
